# Generated by Django 4.0.5 on 2022-06-22 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_delete_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            (
                                "PRICE_INCREASE",
                                "Price of product has increased",
                            ),
                            (
                                "PRICE_DECREASE",
                                "Price of product has decreased",
                            ),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "desc",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.productdetail",
                    ),
                ),
            ],
        ),
    ]
